### ISSUE TITLE
Git Push to Wiki-Repository is not possible

### ISSUE THREAD

**Issue by hirter** [microsoft/vsts-wikiTools#7]
It is not possible to push the migrated files from the local repository to the origin:

error: unpack failed: error The blob object c369b024fcb95da6ee4682eab5c840c1c9cb1ba0 was rejected: The object will increase this repository size by 7772458 bytes (the limit is 4194304 bytes).
To https://[removed].visualstudio.com/DefaultCollection/xxx/_git/xxx.wiki
 ! [remote rejected] wikiMaster -> wikiMaster (The blob object c369b024fcb95da6ee4682eab5c840c1c9cb1ba0 was rejected: The object will increase this repository size by 7772458 bytes (the limit is 4194304 bytes).)

**Comment by snankani** [comment]
this repository is in maintenance and no active is happening, hence we will be archiving this repo.
