### ISSUE TITLE
Work Items not migrated

### ISSUE THREAD

**Issue by ferretiz** [microsoft/vsts-wikiTools#9]
We performed the migration and the links to the work items in the migrated pages are broken. Is there any way to fix this?
![wikiwi1](https://user-images.githubusercontent.com/13686217/27971970-972c594c-6322-11e7-83af-b125e7907631.jpg)

**Comment by sandeepchadda** [comment]
Hi Ferretiz,

I apologize for the inconvenience. We are working on a feature to support linking work items with Wiki. The current VSTS Wiki does not support linking work items.

regards
Sandeep Chadda

**Comment by sandeepchads** [comment]
Hi,

VSTS Wiki now supports referencing work items using #. 

Thanks
Sandee

**Comment by snankani** [comment]
this repository is in maintenance and no active is happening, hence we will be archiving this repo.
